Ranking

In [ ]:
# b1.sort_values(by=["IS03","Country"]) 
# b1.rank(axis=1)  #when dealing with columns we ahve mention axis = 1 and rank orders every column in ascending by default else we have to mention scending = 1

Concatenate

In [3]:
import pandas as pd
import numpy as np

In [4]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                  columns=['letter', 'number'])

df1

  letter  number
0      a       1
1      b       2

In [5]:
df2 = pd.DataFrame([['c', 3], ['d', 4]],
                   columns=['letter', 'number'])
df2

  letter  number
0      c       3
1      d       4

In [7]:
df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                    columns=['letter', 'number', 'animal'])
df3

  letter  number animal
0      c       3    cat
1      d       4    dog

In [6]:
pd.concat([df1, df2])

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [8]:
pd.concat([df1, df3])

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [9]:
pd.concat([df1, df3], join="inner") #only columns common for both data frames are joined togther

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [12]:
drink = pd.read_csv('starbucks-menu-nutrition-drinks.csv')
 
drink.head(5)

,Unnamed: 0,Calories,Fat (g),Carb. (g),Fiber (g),Protein,Sodium
0,Cool Lime Starbucks Refreshers™ Beverage,45,0,11,0,0,10
1,Ombré Pink Drink,-,-,-,-,-,-
2,Pink Drink,-,-,-,-,-,-
3,Strawberry Acai Starbucks Refreshers™ Beverage,80,0,18,1,0,10
4,Very Berry Hibiscus Starbucks Refreshers™ Beve...,60,0,14,1,0,10

Merging & Joining