In [ ]:
import pandas as pd
import numpy as np

b1 =pd.read_csv("endangeredLang.csv")

b1.head(n=4)

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...

In [ ]:
b1.Countries

0                                                   Italy
1                                                   Italy
2       Germany, Denmark, Netherlands, Poland, Russian...
3       Belarus, Latvia, Lithuania, Poland, Russian Fe...
4                                      Italy, Switzerland
                              ...
2717                                                Japan
2718                                             Colombia
2719                                             Colombia
2720                                      India, Pakistan
2721                                                 Oman
Name: Countries, Length: 2722, dtype: object

In [ ]:
a1 = b1[["ID","Countries"]]
a1[2:5]

    ID                                          Countries
2  383  Germany, Denmark, Netherlands, Poland, Russian...
3  335  Belarus, Latvia, Lithuania, Poland, Russian Fe...
4  382                                 Italy, Switzerland

In [ ]:
a2 = b1[b1["Number of speakers"] <5000] 
a1

        ID                                          Countries
0     1022                                              Italy
1     1023                                              Italy
2      383  Germany, Denmark, Netherlands, Poland, Russian...
3      335  Belarus, Latvia, Lithuania, Poland, Russian Fe...
4      382                                 Italy, Switzerland
...    ...                                                ...
2717  1972                                              Japan
2718  2018                                           Colombia
2719  2015                                           Colombia
2720  2716                                    India, Pakistan
2721  2177                                               Oman

[2722 rows x 2 columns]

Column/Row

In [13]:
z1 = pd.DataFrame(b1)
z1

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
...,...,...,...,...,...,...,...,...,...
2717,1972,Yonaguni,Japan,JPN,Severely endangered,NaN,24.4580,122.9802,Yonaguni Island
2718,2018,Yucuna,Colombia,COL,Definitely endangered,NaN,-1.2633,-70.6640,NaN
2719,2015,Yurutí (Colombia),Colombia,COL,Definitely endangered,NaN,1.1370,-70.2136,NaN
2720,2716,Zangskari,"India, Pakistan","IND, PAK",Definitely endangered,NaN,34.0833,76.8500,NaN
2721,2177,Zidgali,Oman,OMN,Critically endangered,NaN,23.4027,58.0957,Capital area of Muscat

In [15]:
z1.drop(z1.index[0],inplace = True)

In [16]:
z1.drop(z1.index[:2],inplace = True)

In [20]:
z1.drop(["Longitude"], axis = 1 )

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Description of the location
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,the region of Lombardy (except the southernmos...
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,"many European countries, most densely in East-..."
6,2211,Yiddish (Israel),Israel,ISR,Definitely endangered,3000000.0,32.0833,"most speakers now live outside Europe, mainly ..."
7,1586,Gondi,India,IND,Vulnerable,2713790.0,19.5804,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand..."
...,...,...,...,...,...,...,...,...
2717,1972,Yonaguni,Japan,JPN,Severely endangered,NaN,24.4580,Yonaguni Island
2718,2018,Yucuna,Colombia,COL,Definitely endangered,NaN,-1.2633,NaN
2719,2015,Yurutí (Colombia),Colombia,COL,Definitely endangered,NaN,1.1370,NaN
2720,2716,Zangskari,"India, Pakistan","IND, PAK",Definitely endangered,NaN,34.0833,NaN
2721,2177,Zidgali,Oman,OMN,Critically endangered,NaN,23.4027,Capital area of Muscat